# Generated by Django 2.1.5 on 2019-04-18 20:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='game.PlayerGameInfo', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='secret_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='guess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 20, 13, 22, 401995)),
        ),
    ]
