# Generated by Django 2.1.5 on 2019-04-18 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190418_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 21, 19, 35, 874072)),
        ),
    ]
