# Generated by Django 2.1.5 on 2019-05-15 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190418_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 19, 40, 28, 291905)),
        ),
    ]
