# Generated by Django 2.1.5 on 2019-05-16 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190515_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='playergameinfo',
            name='player',
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='session_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 21, 27, 40, 561088)),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
