# Generated by Django 2.1.5 on 2019-05-16 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190516_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='session_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 21, 45, 52, 676562)),
        ),
    ]
