# Generated by Django 2.1.5 on 2019-05-16 23:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20190516_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='creator',
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 23, 16, 0, 219850)),
        ),
    ]
