# Generated by Django 2.1.5 on 2019-05-16 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20190516_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 23, 16, 24, 335622)),
        ),
    ]
