# Generated by Django 2.1.5 on 2019-05-17 00:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20190516_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 0, 19, 30, 147012)),
        ),
    ]
