# Generated by Django 2.1.5 on 2019-05-17 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20190517_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='player',
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 0, 53, 1, 135674)),
        ),
    ]
